---
name: blog
title: Blog
author:
  name: Denis Vidog
  email: github@doubleds.ru
  website: https://den4k.space
agg_dicts:
  - name: blog
    keys: [blog]
  - name: tags
    keys: [tags]
  - name: categories
    keys: [category]
  - name: date
    keys: [date]
  - name: featured
    keys: [featured]
generators:
  - name: tags
    source:
      type: database
      name: tags
    template:
      name: blog_tag
    output:
      dir: blog/tags
  - name: categories
    source:
      type: database
      name: categories
    template:
      name: blog_category
    output:
      dir: blog/categories
extras:
  css:
  - url: /css/blog.css
